In [1]:
import torch
import warnings

# Its useless to run on T4, checked in Colab
# Eager implementation is faster compared to the compiled one
# New GPUs are recommended to see the performance gain
torch.cuda.get_device_capability()

(11, 0)

## Basic Usage

In [5]:
def foo(x, y):
    a = torch.sin(x)
    b = torch.cos(y)

    return a + b

opt_foo1 = torch.compile(foo)
print(opt_foo1(torch.randn(10, 10), torch.randn(10, 10)))

tensor([[ 5.6401e-01,  1.7016e-02,  7.4052e-01, -9.0659e-01,  6.4671e-01,
          8.7245e-02,  1.7977e+00,  5.5112e-01,  1.9435e+00,  9.7201e-01],
        [ 5.7107e-04,  1.4846e+00,  9.9307e-01,  7.6449e-01,  1.3303e+00,
          3.4297e-01, -5.4293e-03,  3.3660e-01,  1.5422e+00,  1.4008e-01],
        [ 1.0293e+00,  1.8458e+00, -9.8598e-01,  1.6686e+00,  8.3647e-01,
          8.2349e-01,  1.8490e+00,  4.4677e-01,  1.6510e+00, -1.9842e-01],
        [ 1.9871e+00, -1.4957e-01, -3.2866e-01, -8.3208e-01, -2.7273e-01,
          1.2441e+00, -3.4223e-02,  1.9290e+00,  1.6003e-01, -3.2757e-01],
        [ 1.0509e+00,  5.7475e-01,  4.4471e-01,  7.0422e-01,  9.8131e-01,
         -5.3313e-01,  1.2125e+00, -8.6652e-02,  1.0668e+00,  1.2120e+00],
        [ 1.7042e+00,  9.5717e-01,  8.7913e-01, -1.2441e-03,  3.2436e-01,
          1.1627e+00,  1.4027e+00,  6.2523e-02, -9.0566e-01, -1.5851e-02],
        [ 1.4409e+00, -8.5981e-01,  3.3119e-02,  8.8452e-01, -1.3035e-03,
          1.4828e+00,  9.7782e-0

In [12]:
%timeit - 100
opt_foo1(torch.randn(10, 10, device = 'cuda'), torch.randn(10, 10, device = 'cuda'))

4.37 ns ± 0.247 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


tensor([[ 1.3000, -0.0321, -1.5041, -0.0557,  0.7139,  0.4382,  1.2324,  0.0062,
         -0.0742, -0.5448],
        [-0.0253,  0.5874, -0.4172,  0.9959,  0.7264, -0.2549,  0.5916,  0.3568,
         -0.0798,  0.5314],
        [ 1.6214,  1.0751, -0.0082,  0.3447, -0.3065,  0.2184,  0.5108,  1.1271,
          0.8007,  0.5756],
        [ 1.7139, -0.2640, -0.3761, -0.2455,  0.6209,  0.2857, -0.1122,  1.7876,
         -0.3087,  0.6260],
        [ 1.0469,  1.1744,  0.0434,  0.0370, -0.1157,  1.8040, -0.1989,  1.0322,
          0.0846, -1.6194],
        [ 0.8123,  1.9302,  1.1469,  1.0269,  0.5622, -0.4389,  0.4803,  1.2363,
          1.9761,  1.5659],
        [-0.8656,  0.9414,  1.5235,  1.1013,  0.3155,  0.6850,  0.7362,  1.5552,
          0.2015, -0.3910],
        [ 1.9176,  0.8103, -0.4016,  1.6392,  0.9168, -0.2683, -0.4712,  1.1291,
          0.3128, -0.6004],
        [ 1.1191,  1.7887,  0.8115,  0.0942, -0.1750,  0.1145,  0.0865, -0.5304,
          1.5942,  1.2025],
        [-1.9728, -

In [13]:
%timeit - 100
foo(torch.randn(10, 10, device = 'cuda'), torch.randn(10, 10, device = 'cuda'))

4.69 ns ± 0.133 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


tensor([[-0.0162, -0.7898,  1.6381,  1.5643, -0.1108, -0.2654,  0.5863,  0.9334,
          1.1033, -0.6706],
        [ 0.3943,  1.0844,  0.3496,  1.6927,  0.2109,  1.1553,  1.3847,  0.6356,
         -0.0574,  1.1627],
        [ 0.2621,  0.5943,  0.4157,  0.4317,  1.8410, -0.4729,  1.5114, -0.2023,
          0.9812,  0.3078],
        [ 0.8464,  1.6212,  1.4751, -0.0798,  1.9011,  0.3662, -0.1116,  1.6241,
          0.0856,  0.1323],
        [-0.3066,  1.7269,  0.8605,  0.0395,  0.6983,  0.9367,  0.2309,  1.2733,
         -0.6284,  0.7423],
        [ 0.4229, -0.3339,  0.0346,  1.8498,  0.1150,  0.4196,  1.6279,  0.9852,
          1.4195,  1.0310],
        [ 1.5170,  1.6057,  0.2031,  0.8446, -0.4777, -0.0897,  1.9195, -0.1396,
          0.4616,  1.4747],
        [-0.6079,  0.1111,  1.2372,  1.1059, -0.3938,  1.9976,  0.3073,  0.6892,
          1.3043,  1.6004],
        [ 1.6447, -0.6716,  0.1831,  0.9261,  1.4356,  0.7705,  1.4079,  1.6754,
         -0.6574, -1.1659],
        [-0.6373,  

In [14]:
# Decorator

@torch.compile
def opt_foo2(x, y):
    a = torch.sin(x)
    b = torch.cos(y)

    return a + b

opt_foo2(torch.randn(10, 10, device = 'cuda'), torch.randn(10, 10, device = 'cuda'))

tensor([[-0.9854,  1.0840, -0.3664,  1.8418,  0.8283, -0.1000, -0.3923,  0.7472,
          0.1295,  1.8983],
        [ 0.0748,  0.4837,  1.3895,  1.1097,  0.9346,  0.4411,  1.3153,  1.4955,
          1.7193, -0.5116],
        [ 1.0799,  0.9741,  1.0923,  0.1332, -1.7702,  1.8441,  0.0563,  0.9300,
          0.5956, -0.0144],
        [ 1.1667,  1.5886, -0.1969,  1.2411, -0.4864, -0.7643,  0.8716,  0.3799,
          1.6705, -0.1638],
        [ 0.5684, -0.1317,  1.6773,  0.5819,  0.5804,  0.8921,  0.1759,  1.3960,
          1.6376, -0.1045],
        [ 0.8273,  0.8742,  1.0750, -0.6847,  0.1277,  0.7444,  1.4810,  1.5657,
         -0.8013,  0.3618],
        [ 1.1269, -0.0420,  0.0054,  1.2573, -0.2615,  1.8038,  1.7070,  0.4530,
          1.4501, -0.7431],
        [ 1.1692,  0.8024,  1.6221,  1.5243, -1.4324,  0.9368,  1.1536,  0.1106,
          1.6128,  1.0403],
        [ 0.2571,  1.0266, -0.2948, -0.1377,  0.6179, -0.2333,  0.4565, -0.0430,
         -0.2859,  0.1771],
        [ 1.7509,  

In [15]:
# Using with nn.Module
class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = torch.nn.Linear(100, 10)
    def forward(self, x):
        return torch.nn.functional.relu(self.lin(x))

mod = MyModule()
opt_mod = torch.compile(mod)

opt_mod(torch.randn(10, 100))

tensor([[0.4975, 0.8017, 0.2126, 0.8430, 0.0000, 0.3458, 0.0000, 0.1168, 0.5510,
         0.4983],
        [0.0000, 0.7382, 0.3635, 0.0000, 0.0000, 0.0000, 0.7001, 0.0000, 0.0000,
         0.8859],
        [0.3452, 0.7900, 0.0000, 0.4961, 0.0739, 0.8515, 1.3017, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.6337, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0925, 0.2047,
         0.0000],
        [0.0000, 0.9721, 0.0000, 0.0000, 0.2128, 0.0000, 0.0000, 0.9190, 0.5621,
         0.0000],
        [0.0000, 0.0832, 0.0000, 0.0000, 0.1821, 0.5651, 0.0000, 0.8072, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.7612, 0.2724, 0.2608, 0.0000, 0.0000,
         0.0000],
        [0.0564, 0.0000, 1.0035, 0.9434, 0.7710, 0.0000, 0.1910, 0.0000, 0.0000,
         0.4188],
        [0.4641, 0.0000, 0.0000, 0.0000, 0.2236, 0.1572, 0.0000, 1.2034, 0.2231,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.3015, 0.1333, 0.0000, 0.4584,
         0.1859]], grad_fn=<

In [16]:
# Speed up Benchmarking
def timed(fn):
    start = torch.cuda.Event(enable_timing=True)
    end = torch.cuda.Event(enable_timing=True)
    start.record()
    result = fn()
    end.record()
    torch.cuda.synchronize()

    return result, start.elapsed_time(end) / 1000

def generate(b):
    return (
        torch.randn(b, 3, 128, 182).to(torch.float32).cuda(),
        torch.randint(1000, (b, )).cuda()
    )

N_ITERS = 10

from torchvision.models import densenet121
def init_model():
    return densenet121().to(torch.float32).cuda()

In [47]:
model = init_model()

import torch._dynamo
torch._dynamo.reset()
torch.set_float32_matmul_precision('high') # recommended, try running without this

model_opt = torch.compile(model, mode = 'reduce-overhead', fullgraph=True)

inp = generate(16)[0]

In [53]:
# run this 3-4 times to see the spped-up
# It takes soem time initially for the model to get compiled
with torch.no_grad():
    print(f"Eager: {timed(lambda: model(inp))[1]}")
    print(f"Compile: {timed(lambda: model_opt(inp))[1]}")

# default ~ 0.013765316009521484
# reduce-overhead ~ 0.008926656723022461
# max-autotune ~ 0.00884480857849121 (not sure as the size caused SM availability issue for bs 16)

Eager: 0.012969842910766602
Compile: 0.008802530288696288


In [63]:
# Training benchmark
import numpy as np

model = init_model()
opt = torch.optim.Adam(model.parameters())

def train(mod, data):
    opt.zero_grad(True)
    pred = mod(data[0])
    loss = torch.nn.CrossEntropyLoss()(pred, data[1])
    loss.backward()
    opt.step()

eager_times = []
for i in range(N_ITERS):
    inp = generate(16)
    _, eager_time = timed(lambda: train(model, inp))
    eager_times.append(eager_time)
    print(f"eager train time {i}: {eager_time}")
print("~" * 10)

model = init_model()
opt = torch.optim.Adam(model.parameters())
train_opt = torch.compile(train, mode="reduce-overhead")

compile_times = []
for i in range(N_ITERS):
    inp = generate(16)
    _, compile_time = timed(lambda: train_opt(model, inp))
    compile_times.append(compile_time)
    print(f"compile train time {i}: {compile_time}")
print("~" * 10)

model = init_model()
opt = torch.optim.Adam(model.parameters())
model_opt = torch.compile(model, mode="reduce-overhead")

model_compile_times = []
for i in range(N_ITERS):
    inp = generate(16)
    _, compile_time = timed(lambda: train(model_opt, inp))
    model_compile_times.append(compile_time)
    print(f"compile train time {i}: {compile_time}")
print("~" * 10)

eager_med = np.median(eager_times)
compile_med = np.median(compile_times)
model_compile_med = np.median(model_compile_times)
speedup = eager_med / compile_med
assert(speedup > 1)
print(f"(train) eager median: {eager_med}, compile median: {compile_med}, speedup: {speedup}x")
print("~" * 10)

eager train time 0: 0.04989938354492188
eager train time 1: 0.0439447021484375
eager train time 2: 0.041905353546142575
eager train time 3: 0.0423111457824707
eager train time 4: 0.04173397064208984
eager train time 5: 0.042759727478027344
eager train time 6: 0.04166627883911133
eager train time 7: 0.04206362533569336
eager train time 8: 0.04154611968994141
eager train time 9: 0.04225003051757813
~~~~~~~~~~
compile train time 0: 55.28408984375
compile train time 1: 3.685318359375
compile train time 2: 0.03765531921386719
compile train time 3: 0.030465112686157227
compile train time 4: 0.030319047927856446
compile train time 5: 0.030236528396606444
compile train time 6: 0.029931007385253908
compile train time 7: 0.030063478469848633
compile train time 8: 0.029744375228881837
compile train time 9: 0.029800947189331056
~~~~~~~~~~
compile train time 0: 31.219828125
compile train time 1: 1.7047236328125
compile train time 2: 0.03246184158325195
compile train time 3: 0.03068179130554199
comp